config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to:'pages#about'
  get '/about/help', to:'pages#help'

  resources :demos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demo.rb
class Demo < ApplicationRecord
validates :name, presence: true
validates :description, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
  render plain: "hello world!"
end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController

  def new
    @demo = Demo.new
    
  end
 def create
  @demo = Demo.create(demo_params)
  if @demo.save
    flash[:notice]="Created successfully"
  redirect_to demo_path(@demo)
else
  render 'new'
 end
end

def show
  @demo= Demo.find(params[:id])
end

def edit
  @demo= Demo.find(params[:id])
 
end

def update
  @demo= Demo.find(params[:id])
   if @demo.update(demo_params)
    flash[:notice]="Updated successfully"
    redirect_to demo_path(@demo)
  else
    render 'edit'
end
end
def index
  @demos = Demo.all
end

 private
 def demo_params
  params.require(:demo).permit(:name, :description)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end

def about
	end
def help

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/demos/_code.html.erb
<%if @demo.errors.any?%>
<h2> following are the errors </h2>
<ul>
<%@demo.errors.full_messages.each do |msg|%>
<li> <%=msg%></li>
<%end%>
</ul>
<%end%>
<%= form_for @demo do |f| %>
<p>
<%= f.label :name%> <br>
<%= f.text_field :name%>
</p>
<p>
	<%= f.label :description%> <br>
<%= f.text_area :description%>
</p>

<%= f.submit %>
<% end %>

app/views/demos/edit.html.erb
<h1> "Edit" </h1>

<%if @demo.errors.any?%>
<h2> following are the errors </h2>
<ul>
<%@demo.errors.full_messages.each do |msg|%>
<li> <%=msg%></li>
<%end%>
</ul>
<%end%>
<%= form_for @demo do |f| %>
<p>
<%= f.label :name%> <br>
<%= f.text_field :name%>
</p>
<p>
	<%= f.label :description%> <br>
<%= f.text_area :description%>
</p>

<%= f.submit %>
<% end %>

app/views/demos/index.html.erb
<p>
	<%= link_to "Create" , new_demo_path%>
</p>
<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
	</tr>
	<%@demos.each do|demo|%>
	<tr>
		<td><%=demo.name%></td>
		<td><%=demo.description%></td>
		<td><%= link_to "Edit", edit_demo_path(demo)%></td>
		<td><%= link_to "Show" , demo_path(demo)%></td>
<%end%>
	</tr>
</table>

app/views/demos/new.html.erb
<h1>Create a new demo</h1>

<%if @demo.errors.any?%>
<h2> following are the errors </h2>
<ul>
<%@demo.errors.full_messages.each do |msg|%>
<li> <%=msg%></li>
<%end%>
</ul>
<%end%>
<%= form_for @demo do |f| %>
<p>
<%= f.label :name%> <br>
<%= f.text_field :name%>
</p>
<p>
	<%= f.label :description%> <br>
<%= f.text_area :description%>
</p>

<%= f.submit %>
<% end %>

app/views/demos/show.html.erb
<p>
name:	<%= @demo.name %>
</p>
<p>
description:	<%= @demo.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%flash.each do|name,msg|%>
    <ul>
      <li><%=msg%></li>
    </ul>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is about page </h1>

<p> Welcome to our page</p>

app/views/pages/help.html.erb
<h1>This is help page</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>